const animes = [
    {titulo: "Jujutsu Kaisen",
     imagen: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.themoviedb.org%2Ft%2Fp%2Foriginal%2FuyyMrkDgjnpGFM9dnJEYlUya7O0.jpg&f=1&nofb=1&ipt=745299802cd9238754c540644b6e3d1c889ea64158a0184741d9ebcecd2b3ed0",
     genero:"fantasia oscura", 
     sinopsis: "Mueren todos",
     rating:"9.0"},
    {titulo: "The promised neverland", 
     imagen: ,
     genero:"fantasia oscura", 
     sinopsis: "Mueren todos",
     rating:"9.0"},
    {titulo: "Blue Lock",
     genero:"fantasia oscura", 
     sinopsis: "Mueren todos",
     rating:"9.0"},
    {titulo: "Haikyuu", 
     genero:"deporte", 
     sinopsis: "fiebre de hinata",
     rating:"10.0"},
    {titulo: "Wonder egg priority", 
     genero:"fantasia oscura", 
     sinopsis: "Mueren todos",
     rating:"9.0"}
]